---
title: "SME Credit Risk Analytics"
output:
  flexdashboard::flex_dashboard
runtime: shiny
---

```{r setup}

# Libraries
# library(targets)
# library(keras)
# library(tidymodels)
# library(lime)
# library(corrr)
# library(correlationfunnel)
library(flexdashboard)
library(billboarder)
library(plotly)

# library(tidyverse)
# library(tidyquant)

library(glue)


# load data and model
# churn_data_raw   <- tar_read(churn_data)
# model_keras      <- tar_read(production_model_keras)
# train_test_split <- tar_read(churn_splits)
# rec_obj          <- tar_read(churn_recipe)

# Data Setup

# customer scorecard inputs
# main_vars <- c('tenure', 'Contract', 'InternetService', 'MonthlyCharges', 
#                'OnlineBackup', 'OnlineSecurity', 'DeviceProtection', 
#                'TechSupport', 'StreamingMovies', 'PhoneService')
# commercial_vars <- c('InternetService', 'OnlineBackup', 'OnlineSecurity', 
#                      'DeviceProtection', 'TechSupport', 'StreamingMovies', 
#                      'PhoneService')
# financial_vars <- c('PaymentMethod')
# customer_feature_vars <- c(main_vars, commercial_vars, financial_vars) %>% unique
# 
# # transform original datasset
# churn_data_raw <- churn_data_raw %>% 
#   mutate(
#     tenure_range = case_when(
#       tenure < 12 ~ '< 1 Yr',
#       tenure < 24 ~ '1-2 Yrs',
#       tenure < 36 ~ '2-3 Yrs',
#       tenure >= 36 ~ 'Over 3 Yrs',
#       TRUE ~ 'NA'
#     ),
#     monthly_charge_range = case_when(
#       MonthlyCharges < 20 ~ '< 20 per Month',
#       MonthlyCharges < 50 ~ '20-50 per Month',
#       MonthlyCharges < 100 ~ '50-100 per Month',
#       MonthlyCharges >= 100 ~ 'Over 100 per Month',
#       TRUE ~ 'NA'
#     )
#   ) %>%
#   drop_na() %>%
#   select(Churn, everything())
# 
# 
# # Retrieve train and test sets
# train_tbl_with_ids <- training(train_test_split)
# test_tbl_with_ids  <- testing(train_test_split)
# 
# train_tbl <- select(train_tbl_with_ids, -customerID)
# test_tbl  <- select(test_tbl_with_ids, -customerID)
# 
# x_train_tbl <- bake(rec_obj, new_data = train_tbl) %>% select(-Churn)
# x_test_tbl  <- bake(rec_obj, new_data = test_tbl) %>% select(-Churn)
# 
# y_train_vec <- ifelse(pull(train_tbl, Churn) == 'Yes', 1, 0)
# y_test_vec  <- ifelse(pull(test_tbl, Churn) == 'Yes', 1, 0)
# 
# 
# 
# # setup lime::model_type() function for keras
# assign("model_type.keras.engine.sequential.Sequential", envir = globalenv(), function(x, ...) {
#   "classification"
# })
# # setup lime::predict_model() function for keras
# assign("predict_model.keras.engine.sequential.Sequential", envir = globalenv(), function(x, newdata, type, ...) {
#   pred <- predict_proba(object = x, x = as.matrix(newdata))
#   data.frame(Yes = pred, No = 1 - pred)
# })
# 
# # Test our predict_model() function
# predictions <- predict_model(x = model_keras, newdata = x_test_tbl, type = 'raw') %>%
#     tibble::as_tibble()
# 
# # Run lime() on training set
# explainer <- lime::lime(
#     x     = x_train_tbl,
#     model = model_keras,
#     bin_continuous = TRUE
# )
```

Customer Scorecard {data-orientation=rows}
=============================================================================

Sidebar {.sidebar}
-----------------------------------------------------------------------------

#### Customer ID

#### Credit Risk

Strategies
-----------------------------------------------------------------------------

```{css}
.value-box .value-output,
.value-box .caption {
  font-size: 24px;
}
```

### Product Approved

```{r}
valueBoxOutput("main")
```

### Interest Approved

```{r}
valueBoxOutput("interest")
```

### Limit Approved

```{r}
valueBoxOutput("financial")
```

Customer Analysis
-----------------------------------------------------------------------------
### Contributions to Default (LIME) {data-width=67}

```{r}
billboarderOutput('customer_explanation')
```
### Customer Details {data-width=33}

```{css}
table.dataTable thead {
  display:none;
}
table.dataTable tr.selected td, 
table.dataTable td.selected {
  background-color: #c3dbf7 !important;
  border-color: #c3dbf7 !important;
}
```

```{r}
DT::dataTableOutput('customer_info_tbl')
```
